[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.ruff-lsp]
command = "ruff-lsp"
config.settings = {}


[[language]]
name = "rust"
auto-format = true

[[language]]
name = "python"
language-servers = ["pyright", "ruff-lsp"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
